server:
  port: 9014
spring:
  application:
    name: tensquare‐article-crawler
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.192.129:3306/tensquare_article?characterEncoding=UTF8&&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MySQL
    show‐sql: true
  redis:
    host: 192.168.192.129
ai:
  dataPath: E:/article/
